config/urls.py
from django.contrib import admin
from django.urls import path, include

from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('pybo/', views.index)
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('',views.index, name='index') # / 페이지 url 정의
]

pybo/urls.py
from tkinter.font import names

from django.urls import path

from . import views

app_name = 'pybo' # namespace 추가

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/',views.detail, name='detail'),
    path('answer/create/<int:question_id>',views.answer_create,name="answer_create"),
    path('question/create/',views.question_create,name="question_create"),
    path('question/modify/<int:question_id>/',views.question_modify,name="question_modify"),
    path('question/delete/<int:question_id>/',views.question_delete,name="question_delete"),

    path('comment/create/question/<int:question_id>/', views.comment_create_question,
                name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', views.comment_modify_question,
                name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', views.comment_delete_question,
                name='comment_delete_question'),

    path('comment/create/answer/<int:answer_id>/', views.comment_create_answer,
                name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', views.comment_modify_answer,
                name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', views.comment_delete_answer,
                name='comment_delete_answer'),

]

pybo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import CASCADE


# Create your models here.
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject + ", " +str(self.author)+", "+self.content+", "+str(self.create_date)

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete = models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete = models.CASCADE)

pybo/forms.py
from django import forms

from pybo.models import Question, Answer, Comment


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        # widgets={
        #     'subject':forms.TextInput(attrs={'class':'form-control'}),
        #     'content':forms.Textarea(attrs={'class':'form-control', 'rows':10})
        # }
        labels = {
            'subject':'제목',
            'content':'내용'
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content':'답변내용'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {'content':'댓글내용',}

pybo/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from pybo.forms import QuestionForm, AnswerForm, CommentForm
from pybo.models import Question, Comment, Answer


# Create your views here.
def index(request):
    """
    pybo 목록 출력
    """
    # 입력 인자
    page = request.GET.get('page','1')  # 페이지값이 있으면 해당페이지로, 없으면1 페이지
    # 조회
    question_list = Question.objects.order_by('-create_date')
    # 페이징 처리
    paginator = Paginator(question_list, 10) # 조회한결과 페이지당 10개씪 보이기
    page_obj = paginator.get_page(page) # 조회결과를 한페이지당나눠서 페이지객체로 재생성

    # context = {'question_list':question_list} # 전달할 객체
    context = {'question_list':page_obj}
    return render(request,'pybo/question_list.html', context)
    #return HttpResponse("안녕하세요 pybo에 오신걸 환영합니다.")

def detail(request, question_id):
    """
    pybo 내용 출력
    """
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question,pk=question_id)
    context = {'question':question}
    print('question.author',question.author)
    print('request.user', request.user)
    print('question:', question)
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    pybo 답변 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user #추가한 속성 author 적용
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()

    return render(request, 'pybo/question_detail.html',
                  {'question': question, 'form':form})

    #
    # question.answer_set.create(content=request.POST.get('content'),
    #                           create_date=timezone.now())
    # # 등록 후 redirect로 상세페이지로 이동 localhost:8000/pybo/2/
    # return redirect('pybo:detail', question_id=question.id)

@login_required(login_url='common:login')
def question_create(request):
    """
    pybo 질문 등록
    """
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user # 추가한 속성 author 적용
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')

    else:
        form = QuestionForm()

    return render(request, 'pybo/question_form.html', {'form':form})

@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    pybo 질문 수정
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id = question.id)
    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now() # 수정일시 지정
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)

    context = {'form':form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    pybo 질문 삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제 권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)
    question.delete() #삭제 처리
    return redirect('pybo:index') # index페이지(question list)로 이동


@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    """
    pybo 질문댓글 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save() # db저장
            # return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.question.id),comment.id))
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = CommentForm()

    context = {'form':form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    """
    pybo 질문 댓글 수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('pybo:detail', question_id=comment.question.id)
    else:
        form = CommentForm(instance=comment)

    context = {'form':form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    """
    pybo 질문 댓글 삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.errors(request, '댓글삭제권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.question_id)
    else:
        comment.delete()

    return redirect('pybo:detail', question_id=comment.question_id)

# 답변 댓글 등록
@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    """
    pybo 답변 댓글 등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False) # 메모리 임시저장-db에 미반영
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save() # db에 반영처리
            return redirect('pybo:detail', question_id=comment.answer.question.id)

    else:
        form = CommentForm()

        context = {'form':form}
    return render(request, 'pybo/comment_form.html', context)

# 답변 댓글 등록
@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    """
    pybo 답변 댓글 수정
    """
    pass


# 답변 댓글 등록
@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    """
    pybo 댓글 삭제
    """
    pass

templates/pybo/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control"name="content" id="content"
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
  <h2 class="border-bottom py-2">{{ question.subject }}</h2>
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space:pre-line;">
          {{question.content}}
      </div><!-- card-text -->
      <div class="d-flex justify-content-end">
        {% if question.modify_date %}
        <div class="badge badge-light p-2 text-left  mx-3 ">
          <div class="mb-2">수정 일시</div>
          <div>{{ question.modify_date }}</div>
        </div>
        {% endif %}
        <div class="badge badge-light p-2 text-left">
          <div class="mb-2">{{ question.author.username }}</div>
          <div>{{question.create_date}}</div>
        </div><!-- badge -->
      </div><!-- d-flex -->
      {% if request.user == question.author %} <!-- 작성자와 로그인 아이디가 같으면 수정 가능 -->
      <div class="my-3">
        <a href="{% url 'pybo:question_modify' question.id %}"
             class="btn btn-sm btn-outline-success">수정</a>
<!--        <a href="#"-->
<!--           data-uri="{% url 'pybo:question_delete' question.id %}"-->
<!--             class="delete btn btn-sm btn-outline-warning">삭제</a>-->
        <!-- Button trigger modal -->
        <button type="button" class="delete btn btn-sm btn-outline-warning"
                data-toggle="modal" data-target="#deleteModel"
        data-uri="{% url 'pybo:question_delete' question.id %}"
        >
          삭제
        </button>


      </div>
      {% else %}
      <div class="my-3">
        <a href="#"
             class="btn btn-sm btn-outline-secondary" disabled >수정</a>
        <a href="#"
             class="btn btn-sm btn-outline-secondary" disabled >삭제</a>
      </div>
      {% endif %}

      <!-- 질문 댓글 start -->
      {% if question.comment_set.count > 0 %}
      <div class="mt-3">
        {% for comment in question.comment_set.all %}
          <div class="comment py-2 text-muted">
            <span style="white-space: pre-line;">{{comment.content}}</span>
            <span>
               - {{ comment.author }}, {{ comment.create_date}}
                {% if comment.modify_date %}
                 (수정:{{ comment.modify_date }})
                {% endif %}
            </span>
            {% if request.user == comment.author %}
            <a href="{% url 'pybo:comment_modify_question' comment.id %}"
               class="btn btn-sm btn-outline-success  small">수정</a>
<!--            <a href="#" class="small delete"-->
<!--                data-uri="{% url 'pybo:comment_delete_question' comment.id%}">삭제</a>-->
            <!-- Button trigger modal -->
                <button type="button" class="delete btn btn-sm btn-outline-warning"
                        data-toggle="modal" data-target="#deleteModel"
                data-uri="{% url 'pybo:comment_delete_question' comment.id%}"
                >
                  삭제
                </button>
            {% endif %}
          </div>
        {% endfor %}
      </div>
      {% endif %}
      <div>
        <a href="{% url 'pybo:comment_create_question' question.id %}"
           class="small"><small>댓글 추가 ..</small></a>
      </div>
     <!-- 질문 댓글 end -->
    </div><!-- card-body -->
  </div><!-- card -->

<h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
{% for answer in question.answer_set.all %}
<div class="card my-3">
  <div class="card-body">
    <div class="card-text" style="white-space:pre-line;">
        {{ answer.content }}
    </div><!-- card-text -->
    <div class="d-flex justify-content-end">
      <div class="badge badge-light p-2">
        {{ answer.create_date}}
      </div><!-- badge -->
    </div><!-- d-flex -->
  </div><!-- card-body -->
</div><!-- card -->

 <!-- 답변 댓글 start -->
      {% if answer.comment_set.count > 0 %}
      <div class="mt-3">
        {% for comment in answer.comment_set.all %}
          <div class="comment py-2 text-muted">
            <span style="white-space: pre-line;">{{comment.content}}</span>
            <span>
               - {{ comment.author }}, {{ comment.create_date}}
                {% if comment.modify_date %}
                 (수정:{{ comment.modify_date }})
                {% endif %}
            </span>
            {% if request.user == comment.author %}
            <a href="{% url 'pybo:comment_modify_answer' comment.id %}"
               class="btn btn-sm btn-outline-success  small">수정</a>
            <!-- Button trigger modal -->
                <button type="button" class="delete btn btn-sm btn-outline-warning"
                        data-toggle="modal" data-target="#deleteModel"
                data-uri="{% url 'pybo:comment_delete_answer' comment.id%}"
                >
                  삭제
                </button>
            {% endif %}
          </div>
        {% endfor %}
      </div>
      {% endif %}
      <div>
        <a href="{% url 'pybo:comment_create_answer' answer.id %}"
           class="small"><small>댓글 추가 ..</small></a>
      </div>
     <!-- 답변 댓글 end -->

{% endfor %}

<form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
  {% csrf_token%}
  <!-- 오류 메세지 start -->
  {% if form.errors %}
  <div class="alert alert-danger" role="alert">
    {% for field in form %}
      {% if field.errors %}
        <strong>{{ field.label }}</strong>
        {{ field.errors}}
      {% endif %}
    {% endfor %}
  </div>
  {% endif %}
<!-- 오류 메세지 end -->
  <div class="from-group">
    <textarea name="content" id="content"
              {% if not user.is_authenticated %}disabled{% endif %}
              class="form-control" rows="10"></textarea>
  </div>
  <input type="submit" value="답변 등록" class="btn btn-primary">
  <a href="/pybo/" class="btn btn-success">질문 목록</a>
</form>
</div><!-- container -->
<script>
 $(document).ready(function(){
  let deleteUri = "";

  $('#deleteModel').on('show.bs.modal', function(event){
    const button = $(event.relatedTarget);
    deleteUri = button.data('uri');
  });

  $('.delBtn').on('click', function(){
    if(deleteUri){
      location.href = deleteUri;
      }
   });
 });
</script>
<!-- Modal -->
<div class="modal fade" id="deleteModel" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">삭제하기</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        정말 삭제하시겠습니까?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">취소</button>
        <button type="button"  class="delBtn btn btn-primary">삭제</button>
      </div>
    </div>
  </div>
</div>


{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token%}
<!--    {{ form.as_p}}-->
    <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>

    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">

{% if question_list %}
     <table class="table">
     <thead>
       <tr class="thead-dark">
           <th>번호</th>
           <th style="width:50%">제목</th>
           <th>글쓴이</th>
           <th>작성일자</th>
       </tr>
     </thead>
         <tbody>
      {% for question in question_list %}
       <tr>
           <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
           <td>
                <a href="{% url 'pybo:detail' question.id %}">
                    {{question.subject}}
                    {% if question.answer_set.count > 0 %}
                    <span class="badge badge-danger small ml-2">
                        {{ question.answer_set.count }}
                    </span>
                    {% endif %}
                </a>
           </td>
           <td>{{ question.author.username }}</td> <!-- 글쓴이 추가 -->
           <td>
               {{question.create_date}}
           </td>
       </tr>
           {% endfor %}
         </tbody>
 </table>
<!-- 페이징 처리 -->
    <ul class="pagination justify-content-center">
        <!-- 이전 페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{question_list.previous_page_number}}">
                이전
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" aria-disabled="true"  tabindex="-1">
                이전
            </a>
        </li>
        {% endif %}
        <!-- 페이지 리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number}}">
                    {{page_number}}
                </a>
            </li>
            {% else %}
            <li class="page-item" aria-current="page">
                <a class="page-link" href="?page={{ page_number}}">
                    {{page_number}}
                </a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음 페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">
                다음
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" href="#" aria-disabled="true">
                다음
            </a>
        </li>
        {% endif %}
    </ul>



{% else %}
    <p>질문이 없습니다.</p>
{% endif %}

<a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>

{% endblock %}