common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from common.views import logout_view

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),
    # path('logout/', logout_view, name='logout')
    path('signup/', views.signup, name='signup')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('pybo/', views.index)
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('',views.index, name='index') # / 페이지 url 정의
]

pybo/urls.py
from tkinter.font import names

from django.urls import path

from . import views

app_name = 'pybo' # namespace 추가

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/',views.detail, name='detail'),
    path('answer/create/<int:question_id>',views.answer_create,name="answer_create"),
    path('question/create/',views.question_create,name="question_create"),
    path('question/modify/<int:question_id>/',views.question_modify,name="question_modify"),
    path('question/delete/<int:question_id>/',views.question_delete,name="question_delete"),

    path('comment/create/question/<int:question_id>/', views.comment_create_question,
                name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', views.comment_modify_question,
                name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', views.comment_delete_question,
                name='comment_delete_question'),

    path('comment/create/answer/<int:answer_id>/', views.comment_create_answer,
                name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', views.comment_modify_answer,
                name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', views.comment_delete_answer,
                name='comment_delete_answer'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS-->
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- Jquery JS -->
    <script src="{% static 'jquery-3.7.1.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <!-- pybo CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  <title>Hello, pybo!</title>
</head>
<body>
{% include 'navbar.html' %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content%}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/form_errors.html
{% if form.errors %}
<!-- 필드 오류 출력-->
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        <strong>{{field.label}}</strong>
        {{ error }}
      </div>
    {% endfor %}
  {% endfor %}
  <!-- 넌 필드 오류 -->
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      <strong>{{ errors }}</strong>
    </div>
  {% endfor %}
{% endif %}

templates/navbar.html
<!-- 네비게이션 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
  <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
          data-target="#navbarNav" aria-controls="navbarNav"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        {% if user.is_authenticated %}
        <form action="{% url 'common:logout' %}" method="POST" class="d-inline-block">
          <div class="form-group mb-0">
            {% csrf_token %}
            <button class="nav-link border-0" type="submit" style="vertical-align: middle;">{{ user.username }} (로그아웃)</button>
          </div>
        </form>
        {% else %}
        <a class="nav-link" href="{% url 'common:login' %}" style="display: inline-block; vertical-align: middle;">로그인</a>
        {% endif %}
      </li>
    </ul>
  </div>
</nav>